name: Run ESLint and Cypress on PUSH

on: [push]

jobs:
  eslint:
    name: Lint Action
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v3

      # Install Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      # Install your dependencies
      - run: npm install

      # Run ESLint
      - uses: wearerequired/lint-action@v2.3.0

  cypress:
    name: Cypress
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          project: ./
          browser: electron
          build: npm run build
          start: npm run start
          wait-on: "http://localhost:3000"
